name: Azure DevOps Sync

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Push to Azure DevOps
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "Your Name"
          git remote add azure-devops <Azure DevOps Repo URL>
          git push azure-devops main:main  # Change branch names as needed
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
